sudo: required
services:
  - docker

notifications:
  slack: privateuser-workspace:5hybgvvnXJOVAuc01WiKfrmX

before_install:
  - docker build -t adriankubica/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run adriankubica/react-test npm test -- --coverage

after_success:
  - docker build -t adriankubica/multi-client ./client
  - docker build -t adriankubica/multi-nginx ./nginx
  - docker build -t adriankubica/multi-server ./server
  - docker build -t adriankubica/multi-worker ./worker
  # Log in to the docker CLI
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  # Take thos images and push them to docker hub
  - docker push adriankubica/multi-client
  - docker push adriankubica/multi-nginx
  - docker push adriankubica/multi-server
  - docker push adriankubica/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-844735237674
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"